version: "3.7"

services:
  employees-dev-db:
    container_name: employees-dev-db
    image: postgres:16.0
    restart: always
    volumes:
      - employees-dev-db-volume:/var/lib/postgresql/data
      - ./database/postgres/docker-entrypoint-initdb:/docker-entrypoint-initdb.d/
    environment:
      - POSTGRES_USER=suntrie
      - POSTGRES_PASSWORD=be
      - POSTGRES_DB=employees
    command: ["--autovacuum=off"]
    ports:
      - "127.0.0.1:5432:5432"
  employee-service-zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  employee-service-kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=employee-service-zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - employee-service-zookeeper

volumes:
  employees-dev-db-volume:
    external: true
