version: "3.7"

services:
  employees-dev-db:
    container_name: employees-dev-db
    image: postgres:16.0
    restart: always
    volumes:
      - employees-dev-db-volume:/var/lib/postgresql/data
      - ./database/postgres/docker-entrypoint-initdb:/docker-entrypoint-initdb.d/
      #- ./dump:/home/postgres/dump #TODO
    environment:
      - POSTGRES_USER=suntrie
      - POSTGRES_PASSWORD=be
      - POSTGRES_DB=employees
    command: ["--autovacuum=off"]
    ports:
      - "127.0.0.1:5432:5432"

volumes:
  employees-dev-db-volume:
    external: true
