server:
  port: 8089

spring.datasource.url: jdbc:postgresql://localhost:5432/employees
spring.datasource.username: suntrie
spring.datasource.password: be
spring.liquibase.change-log: classpath:db/changelog/db.changelog-master.xml
spring:
  jpa:
    open-in-view: false
  kafka:
    client-id: employee-service
    bootstrap-servers: 127.0.0.1:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.UUIDSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      enabled: false
      auto-offset-reset: earliest
      group-id: test-group
      key-deserializer: org.apache.kafka.common.serialization.UUIDDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    properties:
      spring.json.trusted.packages: '*'
    topic:
      on-employee-change: on-employee-change-topic


spring.datasource.driver-class-name: org.postgresql.Driver
spring.jpa.show-sql: true
spring.jpa.database: postgresql
spring.jpa.hibernate.ddl-auto: none

springdoc:
  api-docs:
    path: /open-api-docs
  swagger-ui:
    path: /swagger
    tags-sorter: alpha
    operations-sorter: method

logging:
  file:
    name: './log/app.log'
  level:
    root: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
