server:
  port: 8089

spring.datasource.url: jdbc:postgresql://localhost:5432/employees
spring.datasource.username: suntrie #TODO: env
spring.datasource.password: be
spring.liquibase.change-log: classpath:db/changelog/db.changelog-master.xml
spring:
  security:
    filter-order:5

spring.datasource.driver-class-name: org.postgresql.Driver
spring.jpa.show-sql: true
spring.jpa.database: postgresql
spring.jpa.hibernate.ddl-auto: none

springdoc:
  api-docs:
    path: /open-api-docs
  swagger-ui:
    path: /swagger
    tags-sorter: alpha
    operations-sorter: method

logging:
  level:
    root: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG